import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const workspaceDir = '/home/eyobed/Documents/School/BUT/Semester 2/UXIa/Projects/SyncUp';
const SKILL_DIR = '/home/eyobed/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const TMP_DIR = path.join(workspaceDir, '.codex-build-syncup');
const FINAL_PPTX = path.join(workspaceDir, 'report/presentation-output/SyncUp_Presentation_Content_Revision_1.pptx');
const RUNTIME_PYTHON = '/home/eyobed/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const { resolvePresentationFont, finalizePresentation } = await import(pathToFileURL(path.join(SKILL_DIR, 'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont({ fontFamily: 'Aptos' });
const ppt = Presentation.create({ slideSize: { width: 1280, height: 720 } });

const C = { navy:'#0B2239', teal:'#0C7F89', darkTeal:'#075C66', mint:'#D9F3F1', ice:'#F4FBFB', ink:'#0F172A', muted:'#526272', white:'#FFFFFF', line:'#B8D9DA', gold:'#F2B84B' };
const imgDir = path.join(workspaceDir, 'report/assets');
const image = async n => new Uint8Array(await fs.readFile(path.join(imgDir, n)));
const add = (s, text, x, y, w, h, style={}) => {
  const sh=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});
  sh.text=text; sh.text.style={typeface:font,fontSize:style.size??22,color:style.color??C.ink,bold:style.bold??false,autoFit:'shrinkText',paragraphSpacingAfter:0,breakLine:style.breakLine??false,verticalAlignment:style.valign??'top',...style}; return sh;
};
const rect = (s,x,y,w,h,fill,r=22,line='none') => s.shapes.add({geometry:r?'roundRect':'rect',position:{left:x,top:y,width:w,height:h},fill,line:{fill:line,width:line==='none'?0:1},borderRadius:r?'rounded-xl':0});
const line = (s,x,y,w,h,color=C.teal,width=3) => s.shapes.add({geometry:'line',position:{left:x,top:y,width:w,height:h},line:{fill:color,width}});
const base = (title, num, kicker='SYNCUP') => { const s=ppt.slides.add(); s.background.fill=C.ice; add(s,kicker,72,42,220,24,{size:14,bold:true,color:C.teal,letterSpacing:1.8}); add(s,title,72,72,900,55,{size:34,bold:true,color:C.navy}); line(s,72,140,1136,0,C.line,1); add(s,String(num).padStart(2,'0'),1140,42,68,30,{size:15,bold:true,color:C.muted,align:'right'}); return s; };
const screenshot = async (s,name,x,y,w,h) => s.images.add({blob:await image(name),contentType:'image/png',alt:name,fit:'cover',position:{left:x,top:y,width:w,height:h},geometry:'roundRect',borderRadius:'rounded-xl'});
const note = (s, text) => s.speakerNotes.textFrame.setText(`Source: SyncUp technical report, September 2026.\n${text}`);

// 1 Cover
{ const s=ppt.slides.add(); s.background.fill=C.navy; rect(s,0,0,1280,720,C.navy,0); rect(s,730,-80,620,860,C.teal,0); rect(s,870,60,340,580,C.mint,30); await screenshot(s,'campus routing multi floor.png',900,95,280,510); add(s,'SYNCUP',76,76,300,28,{size:17,bold:true,color:C.mint,letterSpacing:3}); add(s,'Meet here.\nFind it.',76,150,590,155,{size:58,bold:true,color:C.white}); add(s,'University appointment scheduling and indoor campus navigation',80,340,500,72,{size:25,color:'#D5E5EE'}); line(s,80,455,200,0,C.gold,5); add(s,'Adar Otieno · Eyobed Awel Nuri · Pengwei Jiang · Mengran Zhao\nFIT VUT · September 2026',80,500,600,58,{size:18,color:C.white}); note(s,'Opening slide.'); }

// 2 problem
{ const s=base('Problem and design premise',2,'THE PROBLEM'); rect(s,72,195,1136,1,C.line,0); const items=[['BOOK','Choose a time that matches a teacher’s availability.'],['LOCATE','Find the room where the consultation will take place.'],['CONNECT','Keep the room information available when planning the route.']]; items.forEach((it,i)=>{const x=72+i*384; add(s,it[0],x,238,285,30,{size:18,bold:true,color:C.teal,letterSpacing:1}); add(s,it[1],x,285,300,120,{size:27,bold:true,color:C.navy}); line(s,x,438,270,0,C.line,2); add(s,['Appointment task','Navigation task','Design link'][i],x,462,290,28,{size:17,color:C.muted});}); add(s,'Design premise: a consultation combines selecting an available time with reaching the stated room. Existing tools can separate these tasks.',72,565,1090,52,{size:25,bold:true,color:C.darkTeal}); note(s,'Design premise based on the supplied technical report. This is not a claim of external user research.'); }

// 3 solution
{ const s=base('Project contribution',3,'WHAT THIS PROJECT ADDS'); rect(s,72,188,360,410,C.white,26,C.line); rect(s,460,188,360,410,C.white,26,C.line); rect(s,848,188,360,410,C.white,26,C.line); add(s,'1',100,218,48,46,{size:34,bold:true,color:C.teal}); add(s,'Earlier component',100,286,290,36,{size:27,bold:true,color:C.navy}); add(s,'The scheduling system and the indoor map originated in earlier course work.',100,340,280,90,{size:20,color:C.muted}); add(s,'2',488,218,48,46,{size:34,bold:true,color:C.teal}); add(s,'Integration work',488,286,290,36,{size:27,bold:true,color:C.navy}); add(s,'This project connects booking data with the map destination in one application.',488,340,280,90,{size:20,color:C.muted}); add(s,'3',876,218,48,46,{size:34,bold:true,color:C.teal}); add(s,'End-to-end flow',876,286,290,36,{size:27,bold:true,color:C.navy}); add(s,'Students select an available slot, provide a topic, and can open the mapped room.',876,340,280,90,{size:20,color:C.muted}); line(s,432,390,28,0,C.gold,4); line(s,820,390,28,0,C.gold,4); add(s,'The contribution is the appointment-location-to-route handoff, not a claim that every future integration is complete.',72,625,1090,29,{size:18,bold:true,color:C.darkTeal}); note(s,'The Czech review notes that the scheduling and map components originated in earlier work. This slide states the integration contribution directly.'); }

// 4 scheduling
{ const s=base('Student scheduling workflow',4,'SCHEDULING'); await screenshot(s,'stud home.png',72,185,430,410); await screenshot(s,'stud book.png',548,185,430,410); rect(s,1012,185,196,410,C.navy,24); add(s,'Find\na professor',1040,224,140,78,{size:25,bold:true,color:C.white}); line(s,1040,330,130,0,C.gold,3); add(s,'View availability by week',1040,360,135,68,{size:20,color:'#DCECEF'}); add(s,'Pick an open slot and add a topic',1040,468,135,78,{size:20,color:'#DCECEF'}); add(s,'Available times are shown in a weekly view before the student books.',72,626,820,30,{size:22,bold:true,color:C.darkTeal}); note(s,'Screens: report/assets/stud home.png and stud book.png. Features: report Results, Scheduling System, For Students.'); }

// 5 availability
{ const s=base('Staff availability controls',5,'SCHEDULING'); await screenshot(s,'prof home.png',72,184,420,414); await screenshot(s,'prof create slots.png',526,184,420,414); add(s,'For staff',986,192,178,28,{size:17,bold:true,color:C.teal,letterSpacing:1.2}); add(s,'Availability makes the student workflow possible',986,238,215,112,{size:30,bold:true,color:C.navy}); add(s,'Staff define recurring availability and can add date-specific slots. The weekly view shows confirmed appointments.',986,392,210,125,{size:20,color:C.muted}); add(s,'Scope note: IS VUT and Google Calendar synchronization are not implemented.',986,548,210,62,{size:17,bold:true,color:C.darkTeal}); note(s,'Screens: report/assets/prof home.png and prof create slots.png. Verified source supports recurring templates and date-specific slots. Calendar integration is out of scope.'); }

// 6 mapping
{ const s=base('Room search and navigation scope',6,'FITMAPS'); await screenshot(s,'campus map.png',72,182,612,420); rect(s,742,196,410,370,C.white,26,C.line); add(s,'Bundled indoor geometry',780,238,320,35,{size:28,bold:true,color:C.navy}); add(s,'The prototype renders FIT indoor geometry and supports pan, zoom, room selection, and text-based room search.',780,300,330,112,{size:21,color:C.muted}); line(s,780,440,278,0,C.line,2); add(s,'Demonstration scope: available FIT campus data, not a verified live campus service.',780,473,315,70,{size:19,bold:true,color:C.darkTeal}); note(s,'Screen: report/assets/campus map.png. The map uses bundled indoor geometry and is presented as a prototype demonstration.'); }

// 7 routing
{ const s=base('Multi-floor route engine',7,'NAVIGATION'); rect(s,72,183,400,420,C.navy,26); add(s,'A101',112,230,210,38,{size:29,bold:true,color:C.white}); line(s,112,293,230,0,C.gold,4); add(s,'Corridor and stair or elevator transition',112,332,254,62,{size:21,color:'#DBEFF0'}); line(s,174,423,0,70,C.mint,3); add(s,'Room destination',112,524,230,32,{size:21,bold:true,color:C.white}); await screenshot(s,'campus routing multi floor.png',520,183,688,420); add(s,'Dijkstra runs on a campus graph. Vertical edges receive an additional weight, so a same-floor path is preferred when it has lower total weight. Route weights remain heuristic and are not validated against observed walking times.',72,620,1110,55,{size:18,bold:true,color:C.darkTeal}); note(s,'Screen: report/assets/campus routing multi floor.png. The code applies Dijkstra to a pre-built graph and adds a heuristic penalty to cross-floor edges.'); }

// 8 integration
{ const s=base('Appointment-to-route handoff',8,'INTEGRATION'); const steps=[['Booking','The booking stores a room when one is defined.'],['Open map','The meeting screen opens the map with that room as the destination.'],['Choose start','The user chooses a known start room; the app renders the route and floor transitions.']]; steps.forEach((a,i)=>{const x=92+i*382; rect(s,x,230,300,220,i===1?C.teal:C.white,24,i===1?C.teal:C.line); add(s,String(i+1).padStart(2,'0'),x+28,254,64,30,{size:17,bold:true,color:i===1?C.mint:C.teal}); add(s,a[0],x+28,302,230,36,{size:28,bold:true,color:i===1?C.white:C.navy}); add(s,a[1],x+28,356,235,80,{size:18,color:i===1?C.white:C.muted}); if(i<2) line(s,x+300,340,82,0,C.gold,4);}); add(s,'Current limitation: the prototype does not determine the user’s live indoor position.',128,548,1010,33,{size:22,bold:true,color:C.darkTeal,align:'center'}); note(s,'The application can pass a meeting location to the map destination. The code uses a supplied or default start room; it has no live indoor positioning.'); }

// 9 architecture
{ const s=base('Evidence, limits, and pilot focus',9,'PROJECT CREDIBILITY'); const boxes=[['Technical foundation','Flutter client\nDijkstra on 1,004 nodes and 2,116 edges\nUnique booking slot key returns HTTP 409 on conflict'],['Verified in the repository','Map-data loading and room lookup\nSame-floor and multi-floor routing\nRoute instructions and app-load widget test'],['Still unverified','External usability and campus route accuracy\nSecurity and load testing\nIS VUT or calendar integration']]; boxes.forEach((a,i)=>{const x=72+i*390; rect(s,x,216,320,280,i===0?C.navy:C.white,24,i===0?C.navy:C.line); add(s,a[0],x+28,250,260,45,{size:24,bold:true,color:i===0?C.white:C.navy}); line(s,x+28,318,120,0,i===0?C.gold:C.teal,3); add(s,a[1],x+28,348,258,110,{size:18,color:i===0?'#DCECEF':C.muted}); if(i<2) line(s,x+320,356,70,0,C.gold,4);}); add(s,'Next decision: can students and staff reliably book and reach a meeting using the combined workflow?',72,565,1135,34,{size:22,bold:true,color:C.darkTeal,align:'center'}); note(s,'Repository checks cover map data, room lookup, routing and instruction generation, plus an app-load widget test. The integrated flow has team manual verification only. No external user study, campus route-accuracy study, security assessment, load test, or calendar integration is complete.'); }

// 10 future
{ const s=base('Next pilot priorities',10,'NEXT STEPS'); add(s,'What the project should validate next',72,195,620,42,{size:30,bold:true,color:C.navy}); const rows=[['Validate the flow','Test booking-to-route completion and reported confusion with students and staff outside the team.'],['Verify the map','Check selected room data and route transitions on campus.'],['Assess integration','Evaluate calendar or IS VUT integration feasibility before wider deployment claims.']]; rows.forEach((r,i)=>{const y=285+i*105; rect(s,72,y,85,62,i===0?C.teal:C.mint,18); add(s,String(i+1),96,y+15,36,28,{size:22,bold:true,color:i===0?C.white:C.darkTeal,align:'center'}); add(s,r[0],190,y+4,340,30,{size:23,bold:true,color:C.navy}); add(s,r[1],190,y+42,650,45,{size:19,color:C.muted});}); rect(s,907,206,300,382,C.navy,30); add(s,'Longer term',951,258,208,35,{size:29,bold:true,color:C.white,align:'center'}); add(s,'BLE positioning\nBroader campus coverage\nAdaptation for other faculties',946,337,220,115,{size:23,bold:true,color:C.mint,align:'center'}); line(s,976,487,160,0,C.gold,4); add(s,'Thank you',954,530,205,35,{size:24,bold:true,color:C.white,align:'center'}); note(s,'Priorities respond directly to the supplied reviews: external testing, campus verification, and integration feasibility precede broader rollout.'); }

const stagingDir=path.join(workspaceDir,'.codex-finalizer'); await fs.mkdir(stagingDir,{recursive:true}); await fs.mkdir(path.dirname(FINAL_PPTX),{recursive:true});
const candidatePath=path.join(stagingDir,'syncup-candidate.pptx'); await (await PresentationFile.exportPptx(ppt)).save(candidatePath);
const result=await finalizePresentation({workspaceDir,candidatePath,finalPath:FINAL_PPTX,pythonExecutable:RUNTIME_PYTHON,integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(stagingDir,'SyncUp_Presentation_Content_Revision_1.validation.json')});
console.log(JSON.stringify({font,final:FINAL_PPTX,result},null,2));
